name: flutter_challenges
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  http: ^1.2.2
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  webview_flutter: ^4.9.0
  google_generative_ai: ^0.4.6
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
